# Generated by Django 3.2 on 2021-05-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_wfi_Community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='value',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
