# Generated by Django 3.2.2 on 2021-05-12 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_wfi_Community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='DownVote_By',
        ),
        migrations.CreateModel(
            name='DownVote_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('val', models.IntegerField(default=0, null=True)),
                ('ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_wfi_Community.answer')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
