# Generated by Django 3.1.7 on 2021-04-06 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_wfi_Community', '0002_comment_downvote_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='AskedBy',
            field=models.ForeignKey(default='Anonymous User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
