# Generated by Django 3.2.1 on 2021-05-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_wfi_Community', '0002_upvote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='downvote',
            name='value',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
