# Generated by Django 3.1.7 on 2021-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_wfi_Community', '0003_auto_20210406_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
