# Generated by Django 3.1.7 on 2021-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_wfi_Community', '0004_comment_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Tags',
            field=models.TextField(null=True),
        ),
    ]
