# Generated by Django 3.2 on 2021-04-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_wfi_Community', '0005_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
